{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION']='0.8'\n",
    "os.environ['XLA_FLAGS']='--xla_gpu_strict_conv_algorithm_picker=false'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from model_flax import CNN\n",
    "import jax\n",
    "import jax.numpy as jnp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "rng = jax.random.PRNGKey(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-05-10 17:23:39.392454: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:727] None of the algorithms provided by cuDNN heuristics worked; trying fallback algorithms.  Conv: (f32[1,28,28,128]{2,1,3,0}, u8[0]{0}) custom-call(f32[1,28,28,1]{2,1,3,0}, f32[3,3,1,128]{1,0,2,3}), window={size=3x3 pad=1_1x1_1}, dim_labels=b01f_01io->b01f, custom_call_target=\"__cudnn$convForward\", backend_config=\"{\\\"conv_result_scale\\\":1,\\\"activation_mode\\\":\\\"0\\\",\\\"side_input_scale\\\":0}\"\n"
     ]
    },
    {
     "ename": "XlaRuntimeError",
     "evalue": "UNKNOWN: Failed to determine best cudnn convolution algorithm for:\n%cudnn-conv = (f32[1,28,28,128]{2,1,3,0}, u8[0]{0}) custom-call(f32[1,28,28,1]{2,1,3,0} %bitcast, f32[3,3,1,128]{1,0,2,3} %copy.1), window={size=3x3 pad=1_1x1_1}, dim_labels=b01f_01io->b01f, custom_call_target=\"__cudnn$convForward\", metadata={op_name=\"jit(conv_general_dilated)/jit(main)/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 28, 28, 1) rhs_shape=(3, 3, 1, 128) precision=None preferred_element_type=None]\" source_file=\"/home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py\" source_line=389}, backend_config=\"{\\\"conv_result_scale\\\":1,\\\"activation_mode\\\":\\\"0\\\",\\\"side_input_scale\\\":0}\"\n\nOriginal error: INTERNAL: All algorithms tried for %cudnn-conv = (f32[1,28,28,128]{2,1,3,0}, u8[0]{0}) custom-call(f32[1,28,28,1]{2,1,3,0} %bitcast, f32[3,3,1,128]{1,0,2,3} %copy.1), window={size=3x3 pad=1_1x1_1}, dim_labels=b01f_01io->b01f, custom_call_target=\"__cudnn$convForward\", metadata={op_name=\"jit(conv_general_dilated)/jit(main)/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 28, 28, 1) rhs_shape=(3, 3, 1, 128) precision=None preferred_element_type=None]\" source_file=\"/home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py\" source_line=389}, backend_config=\"{\\\"conv_result_scale\\\":1,\\\"activation_mode\\\":\\\"0\\\",\\\"side_input_scale\\\":0}\" failed. Falling back to default algorithm.  Per-algorithm errors:\n  Profiling failure on cuDNN engine eng34{k2=2,k19=0,k4=1,k5=0,k6=0,k7=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{k2=3,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng34{k2=1,k19=0,k4=2,k5=1,k6=0,k7=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng34{k2=1,k19=0,k4=3,k5=1,k6=0,k7=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{k2=0,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng2{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{k2=1,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng1{k2=1,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng1{k2=2,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng1{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng38{k18=0,k2=0,k22=2,k23=0,k13=2,k14=3}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng36{k18=1,k2=0,k13=2,k14=3,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng4{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng1{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n\nTo ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mXlaRuntimeError\u001b[0m                           Traceback (most recent call last)",
      "\u001b[1;32m/home/cyanos/Workspace/Thinking_Mazes_Jax/InoteFlax.ipynb Cell 3'\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      <a href='vscode-notebook-cell:/home/cyanos/Workspace/Thinking_Mazes_Jax/InoteFlax.ipynb#ch0000001?line=0'>1</a>\u001b[0m cnn \u001b[39m=\u001b[39m CNN()\n\u001b[0;32m----> <a href='vscode-notebook-cell:/home/cyanos/Workspace/Thinking_Mazes_Jax/InoteFlax.ipynb#ch0000001?line=1'>2</a>\u001b[0m params \u001b[39m=\u001b[39m cnn\u001b[39m.\u001b[39;49minit(rng, jnp\u001b[39m.\u001b[39;49mones([\u001b[39m1\u001b[39;49m, \u001b[39m28\u001b[39;49m, \u001b[39m28\u001b[39;49m, \u001b[39m1\u001b[39;49m]))[\u001b[39m'\u001b[39m\u001b[39mparams\u001b[39m\u001b[39m'\u001b[39m]\n",
      "    \u001b[0;31m[... skipping hidden 11 frame]\u001b[0m\n",
      "File \u001b[0;32m~/Workspace/Thinking_Mazes_Jax/model_flax.py:22\u001b[0m, in \u001b[0;36mCNN.__call__\u001b[0;34m(self, x)\u001b[0m\n\u001b[1;32m     <a href='file:///home/cyanos/Workspace/Thinking_Mazes_Jax/model_flax.py?line=19'>20</a>\u001b[0m \u001b[39m@nn\u001b[39m\u001b[39m.\u001b[39mcompact\n\u001b[1;32m     <a href='file:///home/cyanos/Workspace/Thinking_Mazes_Jax/model_flax.py?line=20'>21</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m__call__\u001b[39m(\u001b[39mself\u001b[39m, x):\n\u001b[0;32m---> <a href='file:///home/cyanos/Workspace/Thinking_Mazes_Jax/model_flax.py?line=21'>22</a>\u001b[0m   x \u001b[39m=\u001b[39m nn\u001b[39m.\u001b[39;49mConv(features\u001b[39m=\u001b[39;49m\u001b[39m128\u001b[39;49m, kernel_size\u001b[39m=\u001b[39;49m(\u001b[39m3\u001b[39;49m, \u001b[39m3\u001b[39;49m))(x)\n\u001b[1;32m     <a href='file:///home/cyanos/Workspace/Thinking_Mazes_Jax/model_flax.py?line=22'>23</a>\u001b[0m   x \u001b[39m=\u001b[39m nn\u001b[39m.\u001b[39mrelu(x)\n\u001b[1;32m     <a href='file:///home/cyanos/Workspace/Thinking_Mazes_Jax/model_flax.py?line=24'>25</a>\u001b[0m   iter_block \u001b[39m=\u001b[39m BasicBlock2D()\n",
      "    \u001b[0;31m[... skipping hidden 3 frame]\u001b[0m\n",
      "File \u001b[0;32m~/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py:389\u001b[0m, in \u001b[0;36m_Conv.__call__\u001b[0;34m(self, inputs)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=385'>386</a>\u001b[0m kernel \u001b[39m=\u001b[39m jnp\u001b[39m.\u001b[39masarray(kernel, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdtype)\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=387'>388</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mshared_weights:\n\u001b[0;32m--> <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=388'>389</a>\u001b[0m   y \u001b[39m=\u001b[39m lax\u001b[39m.\u001b[39;49mconv_general_dilated(\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=389'>390</a>\u001b[0m       inputs,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=390'>391</a>\u001b[0m       kernel,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=391'>392</a>\u001b[0m       strides,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=392'>393</a>\u001b[0m       padding_lax,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=393'>394</a>\u001b[0m       lhs_dilation\u001b[39m=\u001b[39;49minput_dilation,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=394'>395</a>\u001b[0m       rhs_dilation\u001b[39m=\u001b[39;49mkernel_dilation,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=395'>396</a>\u001b[0m       dimension_numbers\u001b[39m=\u001b[39;49mdimension_numbers,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=396'>397</a>\u001b[0m       feature_group_count\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mfeature_group_count,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=397'>398</a>\u001b[0m       precision\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mprecision\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=398'>399</a>\u001b[0m   )\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=399'>400</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=400'>401</a>\u001b[0m   y \u001b[39m=\u001b[39m lax\u001b[39m.\u001b[39mconv_general_dilated_local(\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=401'>402</a>\u001b[0m       lhs\u001b[39m=\u001b[39minputs,\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=402'>403</a>\u001b[0m       rhs\u001b[39m=\u001b[39mkernel,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=409'>410</a>\u001b[0m       precision\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mprecision\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py?line=410'>411</a>\u001b[0m   )\n",
      "    \u001b[0;31m[... skipping hidden 13 frame]\u001b[0m\n",
      "File \u001b[0;32m~/anaconda3/envs/mazes/lib/python3.9/site-packages/jax/_src/dispatch.py:713\u001b[0m, in \u001b[0;36mbackend_compile\u001b[0;34m(backend, built_c, options)\u001b[0m\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/jax/_src/dispatch.py?line=708'>709</a>\u001b[0m \u001b[39m@profiler\u001b[39m\u001b[39m.\u001b[39mannotate_function\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/jax/_src/dispatch.py?line=709'>710</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mbackend_compile\u001b[39m(backend, built_c, options):\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/jax/_src/dispatch.py?line=710'>711</a>\u001b[0m   \u001b[39m# we use a separate function call to ensure that XLA compilation appears\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/jax/_src/dispatch.py?line=711'>712</a>\u001b[0m   \u001b[39m# separately in Python profiling results\u001b[39;00m\n\u001b[0;32m--> <a href='file:///home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/jax/_src/dispatch.py?line=712'>713</a>\u001b[0m   \u001b[39mreturn\u001b[39;00m backend\u001b[39m.\u001b[39;49mcompile(built_c, compile_options\u001b[39m=\u001b[39;49moptions)\n",
      "\u001b[0;31mXlaRuntimeError\u001b[0m: UNKNOWN: Failed to determine best cudnn convolution algorithm for:\n%cudnn-conv = (f32[1,28,28,128]{2,1,3,0}, u8[0]{0}) custom-call(f32[1,28,28,1]{2,1,3,0} %bitcast, f32[3,3,1,128]{1,0,2,3} %copy.1), window={size=3x3 pad=1_1x1_1}, dim_labels=b01f_01io->b01f, custom_call_target=\"__cudnn$convForward\", metadata={op_name=\"jit(conv_general_dilated)/jit(main)/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 28, 28, 1) rhs_shape=(3, 3, 1, 128) precision=None preferred_element_type=None]\" source_file=\"/home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py\" source_line=389}, backend_config=\"{\\\"conv_result_scale\\\":1,\\\"activation_mode\\\":\\\"0\\\",\\\"side_input_scale\\\":0}\"\n\nOriginal error: INTERNAL: All algorithms tried for %cudnn-conv = (f32[1,28,28,128]{2,1,3,0}, u8[0]{0}) custom-call(f32[1,28,28,1]{2,1,3,0} %bitcast, f32[3,3,1,128]{1,0,2,3} %copy.1), window={size=3x3 pad=1_1x1_1}, dim_labels=b01f_01io->b01f, custom_call_target=\"__cudnn$convForward\", metadata={op_name=\"jit(conv_general_dilated)/jit(main)/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 28, 28, 1) rhs_shape=(3, 3, 1, 128) precision=None preferred_element_type=None]\" source_file=\"/home/cyanos/anaconda3/envs/mazes/lib/python3.9/site-packages/flax/linen/linear.py\" source_line=389}, backend_config=\"{\\\"conv_result_scale\\\":1,\\\"activation_mode\\\":\\\"0\\\",\\\"side_input_scale\\\":0}\" failed. Falling back to default algorithm.  Per-algorithm errors:\n  Profiling failure on cuDNN engine eng34{k2=2,k19=0,k4=1,k5=0,k6=0,k7=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{k2=3,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng34{k2=1,k19=0,k4=2,k5=1,k6=0,k7=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng34{k2=1,k19=0,k4=3,k5=1,k6=0,k7=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{k2=0,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng2{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{k2=1,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng1{k2=1,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng1{k2=2,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng1{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng38{k18=0,k2=0,k22=2,k23=0,k13=2,k14=3}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng36{k18=1,k2=0,k13=2,k14=3,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng4{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng1{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n  Profiling failure on cuDNN engine eng28{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'\n\nTo ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning."
     ]
    }
   ],
   "source": [
    "cnn = CNN()\n",
    "params = cnn.init(rng, jnp.ones([1, 28, 28, 1]))['params']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "2f1f03795c8ce0f255458d01ce64668c98eb124149da6a816eabfdbdb486ee95"
  },
  "kernelspec": {
   "display_name": "Python 3.9.12 ('mazes')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
